// Mock product data - this would come from your API/database in a real app
export const products = [
  {
    id: '1',
    name: 'Handcrafted Leather Bag',
    merchant: 'Italian Leatherworks',
    price: 299,
    category: 'Fashion',
    images: [
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    ],
    description: 'This premium handcrafted leather bag is made from the finest Italian leather. Each bag is carefully crafted by skilled artisans with decades of experience in leatherworking. The bag features a spacious main compartment, multiple interior pockets, and adjustable shoulder straps for comfort.',
    features: [
      'Genuine Italian leather',
      'Handcrafted by skilled artisans',
      'Durable brass hardware',
      'Water-resistant lining',
      'Adjustable shoulder strap',
      'Interior pockets for organization',
    ],
    specifications: {
      'Dimensions': '12" x 16" x 4"',
      'Weight': '2.5 lbs',
      'Material': 'Full-grain Italian leather',
      'Color': 'Cognac brown',
      'Warranty': '2-year manufacturer warranty',
    },
    inStock: true,
    featured: true,
    rating: 4.8,
    reviewCount: 42,
    shippingEstimate: '3-5 business days',
    origin: 'Italy',
  },
  {
    id: '2',
    name: 'Premium Coffee Beans',
    merchant: 'Colombian Harvest',
    price: 49,
    category: 'Food & Beverage',
    images: [
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Our premium coffee beans are sourced from high-altitude farms in Colombia. These single-origin beans are carefully selected and roasted to perfection to bring out their unique flavor profile. Each batch is roasted in small quantities to ensure the highest quality and freshness.',
    features: [
      'Single-origin Colombian beans',
      'Ethically sourced and fair trade certified',
      'Medium-dark roast',
      'Notes of chocolate, caramel, and citrus',
      'Whole beans for maximum freshness',
      'Resealable packaging',
    ],
    specifications: {
      'Weight': '1 lb (454g)',
      'Roast Level': 'Medium-dark',
      'Process': 'Washed',
      'Altitude': '1,700-2,000 meters',
      'Harvest': 'Current season',
    },
    inStock: true,
    featured: true,
    rating: 4.5,
    reviewCount: 28,
    shippingEstimate: '3-5 business days',
    origin: 'Colombia',
  },
  // Add more products as needed
];
